#!/bin/bash

main() {
    local result=""
    local response=""
    local curl_output="scrap-release_of-failed.tmp"

    case "$1" in

        ### currently unused
        
        * )
            echo "Exiting '${0}' with code '1' because of unknown key '${1}'"
            return 1
            ;;

    esac

    if [[ -n "${result}" ]] ; then

        echo "${result}"
    else
        echo "ERROR: Exiting '${0}' with code '1' because unable to get version of '$1'"
        echo "ERROR: Unexpected HTTPS response (see '${curl_output}')"
        ### save to file
        echo "${response}" > "../${curl_output}"
        return 1
    fi
}

main $@
