#!/bin/bash

main() {
    local result=""
    local response=""
    local truncateMax=1000

    case "$1" in

        ### currently unused
        
        * )
            echo "Exiting '${0}' with code '1' because of unknown key '${1}'"
            return 1
            ;;

    esac

    if [[ -n "${result}" ]] ; then

        echo "${result}"
    else
        echo "ERROR: Exiting '${0}' with code '1' because unable to get version of '$1'"
        echo "ERROR: Unexpected HTTPS response (truncated to $truncateMax):"
        ### don't use quotes here
        echo ${response:0:truncateMax}
        return 1
    fi
}

main $@
